version: '3'

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ${NGINX_CONFIG}:/etc/nginx/conf.d
            - ${NGINX_LOG}:/var/log/nginx
            - ./nginx/h5bp:/etc/nginx/h5bp
            - ./nginx/mime.types:/etc/nginx/mime.types
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
            - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./nginx/php5.conf:/etc/nginx/php5.conf
            - ./nginx/php71.conf:/etc/nginx/php71.conf
            - ./nginx/php74.conf:/etc/nginx/php74.conf
        depends_on:
            - php5
            - php71
            - php74
        dns:
            - 8.8.8.8
            - 8.8.4.4
        network_mode: "host"

    php5:
        build:
            context: ./php/5.6
            dockerfile: Dockerfile
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ./php/5.6/crontab:/etc/cron.d
            - ./php/5.6/supervisor:/etc/supervisor
        depends_on:
            - elasticsearch
            - mariadb
            - redis
            - rabbitmq
        dns:
            - 8.8.8.8
            - 8.8.4.4
        network_mode: "host"

    php71:
        build:
            context: ./php/7.1
            dockerfile: Dockerfile
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ./php/7.1/supervisor:/etc/supervisor
        depends_on:
            - rabbitmq
            - elasticsearch
            - mariadb
            - mongodb
            - redis
        dns:
            - 8.8.8.8
            - 8.8.4.4
        network_mode: "host"

    php74:
        build:
            context: ./php/7.4
            dockerfile: Dockerfile
        volumes:
            - ${DOCUMENT_ROOT}:/var/www
            - ./php/7.4/supervisor:/etc/supervisor
        depends_on:
            - rabbitmq
            - elasticsearch
            - mariadb
            - mongodb
            - redis
        dns:
            - 8.8.8.8
            - 8.8.4.4
        network_mode: "host"

    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - ${MARIADB_DATA}:/var/lib/mysql/
            - ${MARIADB_IMPORT_DB}:/var/www/databases/
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        dns:
            - 8.8.8.8
            - 8.8.4.4

    elasticsearch:
        build:
            context: ./databases/elasticsearch
            dockerfile: Dockerfile2
        volumes:
            - ${ELASTICSEARCH_LOG}:/var/log/elasticsearch
            - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
            - ${ELASTICSEARCH_CONFIG}:/etc/elasticsearch
            - ${ELASTICSEARCH_KIBANA}/kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - "9200:9200"
            - "9300:9300"
            - "5601:5601"
        dns:
            - 8.8.8.8
            - 8.8.4.4

    # kibana:
    #     image: docker.elastic.co/kibana/kibana:6.6.1
    #     volumes:
    #         - ${ELASTICSEARCH_KIBANA}/kibana.yml:/usr/share/kibana/config/kibana.yml
    #     ports:
    #         - "5601:5601"
    #     network_mode: "host"

    mongodb:
        image: mongo:4.0
        ports:
            - "27017:27017"
        volumes:
            - ./databases/mongodb/logs:/var/log/mongodb
            - ./databases/mongodb/databases:/data/db
            - ./databases/mongodb/configdb:/data/configdb
            - ./databases/mongodb/sample:/var/www/databases
        dns:
            - 8.8.8.8
            - 8.8.4.4

    redis:
        image: redis:latest
        volumes:
            - ${REDIS_DATA}:/data
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - "15672:15672"
            - "5672:5672"
        dns:
            - 8.8.8.8
            - 8.8.4.4
